export const PLACE_TYPES = {
	art_gallery: "Galeries d'art",
	museum: 'Musées',
	performing_arts_theater: 'Théâtres',
	amusement_center: "Centres d'attractions",
	amusement_park: "Parcs d'attractions",
	aquarium: 'Aquariums',
	bowling_alley: 'Bowling',
	casino: 'Casino',
	cultural_center: 'Centres culturels',
	dog_park: 'Parcs pour chiens',
	hiking_area: 'Randonnée',
	historical_landmark: 'Sites historiques',
	marina: 'Marina',
	movie_theater: 'Cinéma',
	national_park: 'Parcs nationaux',
	night_club: 'Boîtes de nuit',
	park: 'Parcs',
	tourist_attraction: 'Attractions touristiques',
	visitor_center: 'Centre des visiteurs',
	zoo: 'Zoo',
	restaurant: 'Restaurants',
	bakery: 'Boulangeries',
	bar: 'Bars',
	cafe: 'Cafés',
	coffee_shop: 'Cafés',
	ice_cream_shop: 'Glaciers'
};
